### ISSUE TITLE
Lab Usability - simplification

### ISSUE THREAD

**Issue by dctootall** [gravwell/training#6]
Identified room for improvement:  
* Most Hands on Labs involve the same repeatable manual steps of ensuring the environment is clean before spinning the lab back up and ingesting the data required for the application exercises.
* Multiple long commands that much be manually entered each time create room for human error and can draw attention to the process of creating/managing docker containers instead of working within the Gravwell application.

Suggestion:    
* create simple bash scripts within the training packet that can be run to automate the docker kill/  rm / create / run steps.
* Script complexity can run from a simple "Run  `DockerClean.sh`" within a lab directory,  to a more complex branching type master script that can automate setting up each exercise in a self contained manner  ( ex:  `GravwellLabs --t basicSearch` )

As training demand expands,   Automation process could also be expanded to leverage functionality like AWS CloudFormation or AMI's to help create complete cloud based training environments for customers to remove some of the initial environment setup complexity.

**Comment by floren** [comment]
We want to make sure each lab is idempotent, so you can drop in and do any experiment at any time, skipping some if you like.

I think there's also value in showing explicitly (via the commands) what commands we're running. Showing a docker command to start the Gravwell core container, then another Docker command to start the ingesters container, then another Docker command to start the netflow generator provides more value to someone who might be *reading through* rather than actually running the commands. Plus, we've taken care to make sure all the commands can be copy-pasted from the PDF into the terminal... if you're working from a paper copy, well, they're not *that* long to type.

For now, we're going to leave things as they are.
